variable "ssh_user" {
  description = "SSH user (ubuntu for Ubuntu AMIs, ec2-user for Amazon Linux)"
  type        = string
  default     = "ubuntu"
}

resource "tls_private_key" "ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_sensitive_file" "ssh_private_key" {
  content          = tls_private_key.ssh_key.private_key_pem
  filename         = "${path.module}/../ssh/aip-intern-generated-key.pem"
  file_permission  = "0600"
  directory_permission = "0700"
}

resource "aws_key_pair" "deployer" {
  key_name   = "aip-intern-deployer-key"
  public_key = tls_private_key.ssh_key.public_key_openssh
}

# Wait for instances to receive public IPs before generating SSH config.
# Stopped instances have no public IP, so we skip the wait in that case.
resource "null_resource" "wait_for_ips" {
  depends_on = [
    aws_ec2_instance_state.gpu_stopped,
    aws_ec2_instance_state.cpu_stopped,
  ]

  triggers = {
    gpu_id         = aws_instance.gpu.id
    cpu_id         = aws_instance.cpu.id
    instance_state = var.instance_state
  }

  provisioner "local-exec" {
    command = <<-EOT
      if [ "${var.instance_state}" != "running" ]; then
        echo "instance_state=${var.instance_state} — skipping IP wait"
        exit 0
      fi
      echo "Waiting for instances to receive public IPs..."
      for i in $(seq 1 60); do
        GPU_IP=$(aws ec2 describe-instances --instance-ids ${aws_instance.gpu.id} \
          --query 'Reservations[0].Instances[0].PublicIpAddress' --output text 2>/dev/null)
        CPU_IP=$(aws ec2 describe-instances --instance-ids ${aws_instance.cpu.id} \
          --query 'Reservations[0].Instances[0].PublicIpAddress' --output text 2>/dev/null)
        if [ "$GPU_IP" != "None" ] && [ -n "$GPU_IP" ] && \
           [ "$CPU_IP" != "None" ] && [ -n "$CPU_IP" ]; then
          echo "Public IPs ready — GPU=$GPU_IP CPU=$CPU_IP"
          exit 0
        fi
        echo "Attempt $i/60 — GPU=$GPU_IP CPU=$CPU_IP — retrying in 5s..."
        sleep 5
      done
      echo "ERROR: Timed out waiting for public IPs after 5 minutes"
      exit 1
    EOT
  }
}

# Read live instance data after IPs are confirmed available.
data "aws_instance" "gpu_live" {
  instance_id = aws_instance.gpu.id
  depends_on  = [null_resource.wait_for_ips]
}

data "aws_instance" "cpu_live" {
  instance_id = aws_instance.cpu.id
  depends_on  = [null_resource.wait_for_ips]
}

resource "local_file" "ssh_config_combined" {
  filename        = "${path.module}/../ssh/aip-intern.conf"
  file_permission = "0600"
  depends_on      = [null_resource.wait_for_ips]

  content = <<-EOF
# aip-intern SSH config (auto-generated by Terraform)
# Add to ~/.ssh/config:  Include ${abspath("${path.module}/../ssh/aip-intern.conf")}

Host aip-intern-gpu
  HostName ${data.aws_instance.gpu_live.public_ip}
  User ${var.ssh_user}
  IdentityFile ${abspath("${path.module}/../ssh/aip-intern-generated-key.pem")}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

Host aip-intern-cpu
  HostName ${data.aws_instance.cpu_live.public_ip}
  User ${var.ssh_user}
  IdentityFile ${abspath("${path.module}/../ssh/aip-intern-generated-key.pem")}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
EOF
}
